- name: Create temporary folder for bash files
  file: path=/tmp/proftpd state=directory

- name: Copy ProFTPd-1.3.3c backdoor
  copy:
      src: files/proftpd-1.3.3c.tar.gz
      dest: /tmp/proftpd
      mode: 0755

- name: Unarchive a file that is already on the remote machine
  unarchive:
      src: /tmp/proftpd/proftpd-1.3.3c.tar.gz
      dest: /tmp/proftpd
      remote_src: yes


- name: Install ProFTPd
  shell:
    cmd: /bin/bash ./configure && /usr/bin/make && /usr/bin/make install
    chdir: /tmp/proftpd/backdoored_proftpd-1.3.3c

- name: Create init.d configuration
  copy:
      src: files/proftpd.init.d
      dest: /etc/init.d/proftpd
      mode: 0755

- name: Create protftpd config directory
  file: path=/etc/proftpd state=directory


- name: Create protftpd logging directory
  file: path=/var/log/proftpd state=directory

- name: Create protfptd etc configuration
  copy:
      src: files/proftpd.config
      dest: /etc/proftpd/proftpd.conf
      mode: 644

