- name: Create temporary folder for bash files
  file: path=/tmp/proftpd state=directory

- name: Create init.d configuration
  copy:
      src: files/proftpd.init.d
      dest: /etc/init.d/proftpd
      mode: 0755

- name: Create protftpd config directory
  file: path=/etc/proftpd state=directory

- name: Create protftpd logging directory
  file: path=/var/log/proftpd state=directory

- name: Create protfptd etc configuration
  copy:
      src: files/proftpd.config
      dest: /etc/proftpd/proftpd.conf
      mode: 644

